export const CONSTAIN = {
  ADDCART: "ADDCART",
  UPQTY: "UPQTY",
  DOWNQTY: "DOWNQTY",
  DELETECART: "DELETECART",
  LOADDATA: "LOADDATA",
  SUMTOTAL: "SUMTOTAL",
  HEART: "HEART",
  SETCOMMENT: "SETCOMMENT",
  COMMENT: "COMMENT"
};
